services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py loaddata main/fixtures/projects.json main/fixtures/skills.json
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com localhost"
      - key: PYTHON_VERSION
        value: "3.11.0"
